COMPROBACIONES

from funciones import obtener_soup

url = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php"

url2 = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php"

soup1 = obtener_soup(url)
soup2 = obtener_soup(url2)

In [166]:
import requests

url = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php#google_vignette"

url2 = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php#google_vignette"

response = requests.get(url)

print(response.status_code)

print(response.text[:1000])

response = requests.get(url2)

print(response.status_code)

print(response.text[:1000])

200
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ligas europeas de fútbol 2024/2025 - Clasificaciones finales y estadísticas | Sport-Histoire</title>
    <meta name="description" content="Clasificaciones finales 2024/2025: Premier League, Ligue 1, La Liga, Bundesliga, Serie A. Resultados de la temporada, mejores ataques y defensas.">
    <link rel="canonical" href="https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php">
    <link rel="alternate" hreflang="fr" href="https://www.sport-histoire.fr/Sport/Football/Championnats/Saison-2024-2025.php">
    <link rel="alternate" hreflang="en" href="https://www.sport-histoire.fr/en/Sport/Football/Leagues/Season-2024-2025.php">
    <link rel="alternate" hreflang="es" href="https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php">
    <link rel="alternate" hreflang="it" href="https://www.
200
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ligas europeas de fútbol 2023/2024 - Clasificaciones finales y estadísticas | Sport-Histoire</title>
    <meta name="description" content="Clasificaciones finales 2023/2024: Premier League, Ligue 1, La Liga, Bundesliga, Serie A. Resultados de la temporada, mejores ataques y defensas.">
    <link rel="canonical" href="https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php">
    <link rel="alternate" hreflang="fr" href="https://www.sport-histoire.fr/Sport/Football/Championnats/Saison-2023-2024.php">
    <link rel="alternate" hreflang="en" href="https://www.sport-histoire.fr/en/Sport/Football/Leagues/Season-2023-2024.php">
    <link rel="alternate" hreflang="es" href="https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php">
    <link rel="alternate" hreflang="it" href="https://www.

In [167]:
def obtener_soup(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    
    return soup

soup1 = obtener_soup(url)
soup2 = obtener_soup(url2)

In [168]:
from bs4 import BeautifulSoup


response1 = requests.get(url)
response2 = requests.get(url2)
    
soup1 = BeautifulSoup(response1.text, "html.parser")
soup2 = BeautifulSoup(response2.text, "html.parser")

print(soup1.title.text)
print(soup2.title.text)

Ligas europeas de fútbol 2024/2025 - Clasificaciones finales y estadísticas | Sport-Histoire
Ligas europeas de fútbol 2023/2024 - Clasificaciones finales y estadísticas | Sport-Histoire

In [169]:
print(soup1.title.text)
print(soup2.title.text)

Ligas europeas de fútbol 2024/2025 - Clasificaciones finales y estadísticas | Sport-Histoire
Ligas europeas de fútbol 2023/2024 - Clasificaciones finales y estadísticas | Sport-Histoire

In [170]:
print(soup1.find_all("a")[:10])

print(soup2.find_all("a")[:10])

[<a class="skip-link" href="#contenu">Saltar al contenido</a>, <a href="/es/">
                Sport<span>-Histoire</span>
</a>, <a aria-current="true" class="active" href="/es/Deporte/index.php">Deporte</a>, <a href="/es/Geografia/index.php">Geografía</a>, <a href="/es/Historia/index.php">Historia</a>, <a class="nav-link-text" href="/es/Deporte/index.php">Deporte</a>, <a class="nav-link-text" href="/es/Deporte/Futbol/Palmares/index.php">Fútbol</a>, <a href="/es/Deporte/Futbol/Campeonatos/index.php">Ligas europeas</a>, <a href="/es/Deporte/Futbol/Palmares/Copa_Mundial.php">Copa del Mundo</a>, <a href="/es/Deporte/Futbol/Palmares/Eurocopa.php">UEFA Euro</a>]
[<a class="skip-link" href="#contenu">Saltar al contenido</a>, <a href="/es/">
                Sport<span>-Histoire</span>
</a>, <a aria-current="true" class="active" href="/es/Deporte/index.php">Deporte</a>, <a href="/es/Geografia/index.php">Geografía</a>, <a href="/es/Historia/index.php">Historia</a>, <a class="nav-link-text" href="/es/Deporte/index.php">Deporte</a>, <a class="nav-link-text" href="/es/Deporte/Futbol/Palmares/index.php">Fútbol</a>, <a href="/es/Deporte/Futbol/Campeonatos/index.php">Ligas europeas</a>, <a href="/es/Deporte/Futbol/Palmares/Copa_Mundial.php">Copa del Mundo</a>, <a href="/es/Deporte/Futbol/Palmares/Eurocopa.php">UEFA Euro</a>]

Primero tenemos que identificar exactamente cuáles de esos enlaces corresponden a competiciones y cuáles son simplemente otros elementos de la web.

In [171]:
for link in soup1.find_all("a"):
    texto1 = link.get_text(strip=True)
    href1 = link.get("href")

    if texto1:
        print(texto1, "->", href1)

Saltar al contenido -> #contenu
Sport-Histoire -> /es/
Deporte -> /es/Deporte/index.php
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Deporte -> /es/Deporte/index.php
Fútbol -> /es/Deporte/Futbol/Palmares/index.php
Ligas europeas -> /es/Deporte/Futbol/Campeonatos/index.php
Copa del Mundo -> /es/Deporte/Futbol/Palmares/Copa_Mundial.php
UEFA Euro -> /es/Deporte/Futbol/Palmares/Eurocopa.php
CAN -> /es/Deporte/Futbol/Palmares/Copa_Africana_de_Naciones.php
Liga de Campeones -> /es/Deporte/Futbol/Palmares/Liga_de_Campeones.php
Más palmarés -> /es/Deporte/Futbol/Palmares/index.php
Fichas de clubes y selecciones -> /es/Deporte/Futbol/Fichas_clubes/index.php
Goles de Zidane en vídeo -> /es/Deporte/Futbol/goles-zidane-francia.php
Rugby -> /es/Deporte/Rugby/Palmares/index.php
Copa del Mundo -> /es/Deporte/Rugby/Palmares/Copa_Mundial.php
Torneo de las 6 Naciones -> /es/Deporte/Rugby/Palmares/Torneo_de_las_Seis_Naciones.php
Copa de Campeones -> /es/Deporte/Rugby/Palmares/Copa_de_Campeones_Europeos.php
Top 14 -> /es/Deporte/Rugby/Palmares/Top_14.php
Copa Desafío -> /es/Deporte/Rugby/Palmares/Copa_Desafio_Europeo_de_Rugby.php
Otras competiciones -> /es/Deporte/Rugby/Palmares/index.php
Tenis -> /es/Deporte/Tenis/Palmares/index.php
Abierto de Australia -> /es/Deporte/Tenis/Palmares/index.php#open-australie
Roland Garros -> /es/Deporte/Tenis/Palmares/index.php#roland-garros
Wimbledon -> /es/Deporte/Tenis/Palmares/index.php#wimbledon
US Open -> /es/Deporte/Tenis/Palmares/index.php#us-open
Otras competiciones -> /es/Deporte/Tenis/Palmares/index.php
Ciclismo -> /es/Deporte/Ciclismo/Palmares/index.php
Tour de Francia -> /es/Deporte/Ciclismo/Palmares/Tour-de-France.php
Tour de Francia Femenino -> /es/Deporte/Ciclismo/Palmares/Tour-de-Francia-Femenino.php
Giro de Italia -> /es/Deporte/Ciclismo/Palmares/Giro_de_Italia.php
Vuelta -> /es/Deporte/Ciclismo/Palmares/Vuelta_a_Espana.php
Otras competiciones -> /es/Deporte/Ciclismo/Palmares/index.php
Baloncesto -> /es/Deporte/Baloncesto/Palmares/index.php
Fútbol americano -> /es/Deporte/Futbol_americano/Palmares/index.php
Balonmano -> /es/Deporte/Balonmano/Palmares/index.php
Automovilismo -> /es/Deporte/Automovilismo/index.php
Vela -> /es/Deporte/Vela/Palmares/index.php
Carreras a pie -> /es/Deporte/Carreras_a_pie/index.php
Trail running -> /es/Deporte/Trail_running/Palmares/index.php
Maratón -> /es/Deporte/Maraton/Palmares/index.php
Triatlón -> /es/Deporte/Triatlon/Palmares/index.php
JJ.OO. Verano -> /es/Deporte/JJOO-Verano/index.php
JJ.OO. Invierno -> /es/Deporte/JJOO-Invierno/index.php
Biografías de deportistas -> /es/Deporte/index.php#biographies
Inicio -> /es/
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Inicio -> /
Deporte -> https://www.sport-histoire.fr/es/Deporte/index.php
Fútbol -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/index.php
2026/2027 -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/index.php
2025/2026Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2025-2026.php
2024/2025Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php
2023/2024Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php
PLPremier League1Liverpool84 pts2Arsenal74 pts3Manchester City71 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/Premier-League-2024-2025.php
L1Ligue 11París Saint-Germain84 pts2Olympique de Marsella65 pts3Mónaco61 ptsJornada 34→ Analizar -> /es/Deporte/Futbol/Campeonatos/Ligue-1-2024-2025.php
LigaLa Liga1FC Barcelona88 pts2Real Madrid84 pts3Atlético de Madrid76 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/La-Liga-2024-2025.php
BLBundesliga1Bayern de Múnich82 pts2Bayer Leverkusen69 pts3Eintracht Fráncfort60 ptsJornada 34→ Analizar -> /es/Deporte/Futbol/Campeonatos/Bundesliga-2024-2025.php
SASerie A1Napoli82 pts2Inter de Milán81 pts3Atalanta74 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/Serie-A-2024-2025.php
París Saint-Germain -> /es/Deporte/Futbol/Clubs/Palmares_Paris_Saint-Germain.php
Villarreal CF -> /es/Deporte/Futbol/Clubs/Palmares_Villarreal_CF.php
Premier League→ -> /es/Deporte/Futbol/Campeonatos/Premier-League.php
Ligue 1→ -> /es/Deporte/Futbol/Campeonatos/Ligue-1.php
La Liga→ -> /es/Deporte/Futbol/Campeonatos/La-Liga.php
Bundesliga→ -> /es/Deporte/Futbol/Campeonatos/Bundesliga.php
Serie A→ -> /es/Deporte/Futbol/Campeonatos/Serie-A.php
Sport-Histoire.fr -> /es/
Deporte -> /es/Deporte/index.php
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Contacto -> /es/contacto
Acerca de -> /es/acerca-de

In [172]:
for link in soup2.find_all("a"):
    texto2 = link.get_text(strip=True)
    href2 = link.get("href")

    if texto2:
        print(texto2, "->", href2)

Saltar al contenido -> #contenu
Sport-Histoire -> /es/
Deporte -> /es/Deporte/index.php
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Deporte -> /es/Deporte/index.php
Fútbol -> /es/Deporte/Futbol/Palmares/index.php
Ligas europeas -> /es/Deporte/Futbol/Campeonatos/index.php
Copa del Mundo -> /es/Deporte/Futbol/Palmares/Copa_Mundial.php
UEFA Euro -> /es/Deporte/Futbol/Palmares/Eurocopa.php
CAN -> /es/Deporte/Futbol/Palmares/Copa_Africana_de_Naciones.php
Liga de Campeones -> /es/Deporte/Futbol/Palmares/Liga_de_Campeones.php
Más palmarés -> /es/Deporte/Futbol/Palmares/index.php
Fichas de clubes y selecciones -> /es/Deporte/Futbol/Fichas_clubes/index.php
Goles de Zidane en vídeo -> /es/Deporte/Futbol/goles-zidane-francia.php
Rugby -> /es/Deporte/Rugby/Palmares/index.php
Copa del Mundo -> /es/Deporte/Rugby/Palmares/Copa_Mundial.php
Torneo de las 6 Naciones -> /es/Deporte/Rugby/Palmares/Torneo_de_las_Seis_Naciones.php
Copa de Campeones -> /es/Deporte/Rugby/Palmares/Copa_de_Campeones_Europeos.php
Top 14 -> /es/Deporte/Rugby/Palmares/Top_14.php
Copa Desafío -> /es/Deporte/Rugby/Palmares/Copa_Desafio_Europeo_de_Rugby.php
Otras competiciones -> /es/Deporte/Rugby/Palmares/index.php
Tenis -> /es/Deporte/Tenis/Palmares/index.php
Abierto de Australia -> /es/Deporte/Tenis/Palmares/index.php#open-australie
Roland Garros -> /es/Deporte/Tenis/Palmares/index.php#roland-garros
Wimbledon -> /es/Deporte/Tenis/Palmares/index.php#wimbledon
US Open -> /es/Deporte/Tenis/Palmares/index.php#us-open
Otras competiciones -> /es/Deporte/Tenis/Palmares/index.php
Ciclismo -> /es/Deporte/Ciclismo/Palmares/index.php
Tour de Francia -> /es/Deporte/Ciclismo/Palmares/Tour-de-France.php
Tour de Francia Femenino -> /es/Deporte/Ciclismo/Palmares/Tour-de-Francia-Femenino.php
Giro de Italia -> /es/Deporte/Ciclismo/Palmares/Giro_de_Italia.php
Vuelta -> /es/Deporte/Ciclismo/Palmares/Vuelta_a_Espana.php
Otras competiciones -> /es/Deporte/Ciclismo/Palmares/index.php
Baloncesto -> /es/Deporte/Baloncesto/Palmares/index.php
Fútbol americano -> /es/Deporte/Futbol_americano/Palmares/index.php
Balonmano -> /es/Deporte/Balonmano/Palmares/index.php
Automovilismo -> /es/Deporte/Automovilismo/index.php
Vela -> /es/Deporte/Vela/Palmares/index.php
Carreras a pie -> /es/Deporte/Carreras_a_pie/index.php
Trail running -> /es/Deporte/Trail_running/Palmares/index.php
Maratón -> /es/Deporte/Maraton/Palmares/index.php
Triatlón -> /es/Deporte/Triatlon/Palmares/index.php
JJ.OO. Verano -> /es/Deporte/JJOO-Verano/index.php
JJ.OO. Invierno -> /es/Deporte/JJOO-Invierno/index.php
Biografías de deportistas -> /es/Deporte/index.php#biographies
Inicio -> /es/
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Inicio -> /
Deporte -> https://www.sport-histoire.fr/es/Deporte/index.php
Fútbol -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/index.php
2026/2027 -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/index.php
2025/2026Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2025-2026.php
2024/2025Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2024-2025.php
2023/2024Clasificación final -> https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Temporada-2023-2024.php
PLPremier League1Manchester City91 pts2Arsenal89 pts3Liverpool82 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/Premier-League-2023-2024.php
L1Ligue 11París Saint-Germain76 pts2Mónaco67 pts3Brest61 ptsJornada 34→ Analizar -> /es/Deporte/Futbol/Campeonatos/Ligue-1-2023-2024.php
LigaLa Liga1Real Madrid95 pts2FC Barcelona85 pts3Girona FC81 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/La-Liga-2023-2024.php
BLBundesliga1Bayer Leverkusen90 pts2VfB Stuttgart73 pts3Bayern de Múnich72 ptsJornada 34→ Analizar -> /es/Deporte/Futbol/Campeonatos/Bundesliga-2023-2024.php
SASerie A1Inter de Milán94 pts2AC Milan75 pts3Juventus de Turín71 ptsJornada 38→ Analizar -> /es/Deporte/Futbol/Campeonatos/Serie-A-2023-2024.php
Bayer Leverkusen -> /es/Deporte/Futbol/Clubs/Palmares_Bayer_Leverkusen.php
Manchester City -> /es/Deporte/Futbol/Clubs/Palmares_Manchester_City.php
Premier League→ -> /es/Deporte/Futbol/Campeonatos/Premier-League.php
Ligue 1→ -> /es/Deporte/Futbol/Campeonatos/Ligue-1.php
La Liga→ -> /es/Deporte/Futbol/Campeonatos/La-Liga.php
Bundesliga→ -> /es/Deporte/Futbol/Campeonatos/Bundesliga.php
Serie A→ -> /es/Deporte/Futbol/Campeonatos/Serie-A.php
Sport-Histoire.fr -> /es/
Deporte -> /es/Deporte/index.php
Geografía -> /es/Geografia/index.php
Historia -> /es/Historia/index.php
Contacto -> /es/contacto
Acerca de -> /es/acerca-de

In [173]:
url_liga_1 = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/La-Liga-2024-2025.php"

response = requests.get(url_liga_1)

soup_liga1 = BeautifulSoup(response.text, "html.parser")

tabla1 = soup_liga1.find("table")

print(tabla1.get_text(" ", strip=True))

Pos ▼ Equipo J G E P GF GC DG Pts Puntos ▼ Forma

In [174]:
url_liga_2 = "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/La-Liga-2023-2024.php"

response = requests.get(url_liga_2)

soup_liga2 = BeautifulSoup(response.text, "html.parser")

tabla2 = soup_liga2.find("table")

print(tabla2.get_text(" ", strip=True))

Pos ▼ Equipo J G E P GF GC DG Pts Puntos ▼ Forma

In [175]:
filas1 = tabla1.find_all("tr")

for fila in filas1:
    columnas1 = fila.find_all(["th", "td"])
    print([columna.get_text(strip=True) for columna in columnas1])

['Pos▼', 'Equipo', 'J', 'G', 'E', 'P', 'GF', 'GC', 'DG', 'Pts', 'Puntos▼', 'Forma']

In [176]:
filas2 = tabla2.find_all("tr")

for fila in filas2:
    columnas2 = fila.find_all(["th", "td"])
    print([columna.get_text(strip=True) for columna in columnas2])

['Pos▼', 'Equipo', 'J', 'G', 'E', 'P', 'GF', 'GC', 'DG', 'Pts', 'Puntos▼', 'Forma']

In [177]:
datos1 = []

for fila1 in filas1[1:]:
    columnas1 = fila1.find_all("td")

    if columnas1:
        equipo = columnas1[1].get_text(strip=True)
        goles_favor = columnas1[6].get_text(strip=True)
        goles_contra = columnas1[7].get_text(strip=True)
        puntos = columnas1[9].get_text(strip=True)

        datos1.append([
            "Competición 2024-2025",
            equipo,
            puntos,
            goles_favor,
            goles_contra
        ])

print(datos1)

[]

In [178]:
datos2 = []

for fila2 in filas2[1:]:
    columnas2 = fila2.find_all("td")

    if columnas2:
        equipo = columnas2[1].get_text(strip=True)
        goles_favor = columnas2[6].get_text(strip=True)
        goles_contra = columnas2[7].get_text(strip=True)
        puntos = columnas2[9].get_text(strip=True)

        datos2.append([
            "Competición 2023-2024",
            equipo,
            puntos,
            goles_favor,
            goles_contra
        ])

print(datos2)

[]

In [179]:
for fila1 in filas1:
    print(fila1)

<tr>
<th data-col="rank" data-type="num">Pos <span class="sort-arrow active" id="sa-rank">▼</span></th>
<th data-col="team" data-type="str">Equipo <span class="sort-arrow" id="sa-team"></span></th>
<th data-col="played" data-type="num">J <span class="sort-arrow" id="sa-played"></span></th>
<th class="hide-mobile" data-col="won" data-type="num">G <span class="sort-arrow" id="sa-won"></span></th>
<th class="hide-mobile" data-col="drew" data-type="num">E <span class="sort-arrow" id="sa-drew"></span></th>
<th class="hide-mobile" data-col="lost" data-type="num">P <span class="sort-arrow" id="sa-lost"></span></th>
<th class="hide-mobile" data-col="gf" data-type="num">GF <span class="sort-arrow" id="sa-gf"></span></th>
<th class="hide-mobile" data-col="ga" data-type="num">GC <span class="sort-arrow" id="sa-ga"></span></th>
<th class="hide-mobile" data-col="gd" data-type="num">DG <span class="sort-arrow" id="sa-gd"></span></th>
<th data-col="pts" data-type="num" id="th-pts" style="display:none;">Pts <span class="sort-arrow" id="sa-pts"></span></th>
<th data-col="indicator" data-type="num" id="th-indicator"><strong>Puntos</strong> <span class="sort-arrow active" id="sa-indicator">▼</span></th>
<th data-col="form" data-type="num">Forma <span class="sort-arrow" id="sa-form"></span></th>
</tr>

In [180]:
for fila2 in filas2:
    print(fila2)

<tr>
<th data-col="rank" data-type="num">Pos <span class="sort-arrow active" id="sa-rank">▼</span></th>
<th data-col="team" data-type="str">Equipo <span class="sort-arrow" id="sa-team"></span></th>
<th data-col="played" data-type="num">J <span class="sort-arrow" id="sa-played"></span></th>
<th class="hide-mobile" data-col="won" data-type="num">G <span class="sort-arrow" id="sa-won"></span></th>
<th class="hide-mobile" data-col="drew" data-type="num">E <span class="sort-arrow" id="sa-drew"></span></th>
<th class="hide-mobile" data-col="lost" data-type="num">P <span class="sort-arrow" id="sa-lost"></span></th>
<th class="hide-mobile" data-col="gf" data-type="num">GF <span class="sort-arrow" id="sa-gf"></span></th>
<th class="hide-mobile" data-col="ga" data-type="num">GC <span class="sort-arrow" id="sa-ga"></span></th>
<th class="hide-mobile" data-col="gd" data-type="num">DG <span class="sort-arrow" id="sa-gd"></span></th>
<th data-col="pts" data-type="num" id="th-pts" style="display:none;">Pts <span class="sort-arrow" id="sa-pts"></span></th>
<th data-col="indicator" data-type="num" id="th-indicator"><strong>Puntos</strong> <span class="sort-arrow active" id="sa-indicator">▼</span></th>
<th data-col="form" data-type="num">Forma <span class="sort-arrow" id="sa-form"></span></th>
</tr>

Con estos código estoy recorriendo las filas de una tabla HTML y sacando el nombre/identificador del equipo que está guardado en data-team. Busco en la fila <tr> de tabla1 y tabla 2.

MEJORA A UNA FUNCIÓN. FUNCION SACAR NOMBRE DE HTML

In [181]:
filas1 = tabla1.find_all("tr")

for fila1 in filas1[1:]:
    print(fila1.get("data-team"))

In [182]:
filas2 = tabla2.find_all("tr")

for fila2 in filas2[1:]:
    print(fila2.get("data-team"))

In [183]:
for fila1 in filas1[1:]:
    print(fila1.get_text(" ", strip=True))

In [184]:
for fila2 in filas2[1:]:
    print(fila2.get_text(" ", strip=True))

In [185]:
equipos1 = tabla1.find_all(attrs={"data-col": "team"})

for equipo1 in equipos1:
    print(equipo1.get_text(strip=True))

Equipo

In [186]:
equipos2 = tabla2.find_all(attrs={"data-col": "team"})

for equipo2 in equipos2:
    print(equipo2.get_text(strip=True))

Equipo

In [187]:
print(len(tabla1.find_all("tr")))

1

In [188]:
print(len(tabla2.find_all("tr")))

1

CON ESTE CONDIGO EN CAMBIO ESTOY COMPROVANDI DÓNDE ESTÁN LOS DATOS DENTRO DE HTML. 

Busco los scripts de la pagina y los guardo y luego los muestro.

In [189]:
scripts1 = soup_liga1.find_all("script")

print(len(scripts1))

for script1 in scripts1:

    if "Barcelona" in script1.get_text():

        print(script1.get_text()[:3000])


scripts2 = soup_liga2.find_all("script")

print(len(scripts2))

for script2 in scripts2:

    if "Barcelona" in script2.get_text():

        print(script2.get_text()[:3000])

19
{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"La Liga 2024/2025: ¿quién lidera la clasificación?","acceptedAnswer":{"@type":"Answer","text":"Líder: FC Barcelona, con 88 puntos en 38 partidos (2,32 puntos por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿qué equipo tiene el mejor ataque?","acceptedAnswer":{"@type":"Answer","text":"Mejor ataque: FC Barcelona, con 102 goles marcados (2,68 goles por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿qué equipo tiene la mejor defensa?","acceptedAnswer":{"@type":"Answer","text":"Mejor defensa: Athletic Club, con 29 goles encajados (0,76 goles por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿cuántas jornadas se han disputado?","acceptedAnswer":{"@type":"Answer","text":"Se han disputado 38 jornadas esta temporada."}}]}

window.standingsData   = [{"team":"FC Barcelona","played":38,"pts":"88","won":"28","drew":"4","lost":"6","gf":"102","ga":"39","gd":"63","form":["W","W","W","L","W"],"form_detail":[{"r":"L","gf":1,"ga":2,"opp":"Club Atlético de Madrid","isHome":true,"opp_display":"Atlético de Madrid"},{"r":"D","gf":1,"ga":1,"opp":"Getafe CF","isHome":false,"opp_display":"Getafe CF"},{"r":"W","gf":7,"ga":1,"opp":"Valencia CF","isHome":true,"opp_display":"Valencia CF"},{"r":"W","gf":1,"ga":0,"opp":"Deportivo Alavés","isHome":true,"opp_display":"Deportivo Alavés"},{"r":"W","gf":4,"ga":1,"opp":"Sevilla FC","isHome":false,"opp_display":"Sevilla FC"},{"r":"W","gf":1,"ga":0,"opp":"Rayo Vallecano de Madrid","isHome":true,"opp_display":"Rayo Vallecano"},{"r":"W","gf":2,"ga":0,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":4,"ga":0,"opp":"Real Sociedad de Fútbol","isHome":true,"opp_display":"Real Sociedad"},{"r":"W","gf":4,"ga":2,"opp":"Club Atlético de Madrid","isHome":false,"opp_display":"Atlético de Madrid"},{"r":"W","gf":3,"ga":0,"opp":"CA Osasuna","isHome":true,"opp_display":"CA Osasuna"},{"r":"W","gf":4,"ga":1,"opp":"Girona FC","isHome":true,"opp_display":"Girona FC"},{"r":"D","gf":1,"ga":1,"opp":"Real Betis Balompié","isHome":true,"opp_display":"Real Betis"},{"r":"W","gf":1,"ga":0,"opp":"CD Leganés","isHome":false,"opp_display":"CD Leganés"},{"r":"W","gf":4,"ga":3,"opp":"RC Celta de Vigo","isHome":true,"opp_display":"RC Celta"},{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":true,"opp_display":"RCD Mallorca"},{"r":"W","gf":2,"ga":1,"opp":"Real Valladolid CF","isHome":false,"opp_display":"Real Valladolid CF"},{"r":"W","gf":4,"ga":3,"opp":"Real Madrid CF","isHome":true,"opp_display":"Real Madrid"},{"r":"W","gf":2,"ga":0,"opp":"RCD Espanyol de Barcelona","isHome":false,"opp_display":"RCD Espanyol"},{"r":"L","gf":2,"ga":3,"opp":"Villarreal CF","isHome":true,"opp_display":"Villarreal CF"},{"r":"W","gf":3,"ga":0,"opp":"Athletic Club","isHome":false,"opp_display":"Athletic Club"}],"display_name":"FC Barcelona","pts_per_game":2.32,"gf_per_game":2.68,"ga_per_game":1.03,"splits":{"away":{"team":"FC Barcelona","side":"away","played":19,"won":"14","drew":"3","lost":"2","gf":"50","ga":"19"},"home":{"team":"FC Barcelona","side":"home","played":19,"won":"14","drew":"1","lost":"4","gf":"52","ga":"20"}},"home_win_pct":73.7,"away_win_pct":73.7},{"team":"Real Madrid CF","played":38,"pts":"84","won":"26","drew":"6","lost":"6","gf":"78","ga":"38","gd":"40","form":["W","L","W","W","W"],"form_detail":[{"r":"W","gf":2,"ga":1,"opp":"Valencia CF","isHome":false,"opp_display":"Valencia CF"},{"r":"W","gf":4,"ga":1,"opp":"UD Las Palmas","isHome":true,"opp_display":"UD Las Palmas"},{"r":"W","gf":3,"ga":0,"opp":"Real Valladolid CF","isHome":false,"opp_display":"Real Valladolid CF"},{"r":"L","gf":0,"ga":1,"opp":"RCD Espanyol de Barcelona","isHome":false,"opp_display":"RCD Espanyol"},{"r":"D","gf":1,"ga":1,"opp":"Club Atlético de Madrid","isHome":true,"opp_di
19

window.standingsData   = [{"team":"Real Madrid CF","played":38,"pts":"95","won":"29","drew":"8","lost":"1","gf":"87","ga":"26","gd":"61","form":["W","W","W","D","D"],"form_detail":[{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":true,"opp_display":"RCD Mallorca"},{"r":"W","gf":3,"ga":2,"opp":"UD Almería","isHome":true,"opp_display":"UD Almería"},{"r":"W","gf":2,"ga":1,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":2,"ga":0,"opp":"Getafe CF","isHome":false,"opp_display":"Getafe CF"},{"r":"D","gf":1,"ga":1,"opp":"Club Atlético de Madrid","isHome":true,"opp_display":"Atlético de Madrid"},{"r":"W","gf":4,"ga":0,"opp":"Girona FC","isHome":true,"opp_display":"Girona FC"},{"r":"D","gf":1,"ga":1,"opp":"Rayo Vallecano de Madrid","isHome":false,"opp_display":"Rayo Vallecano"},{"r":"W","gf":1,"ga":0,"opp":"Sevilla FC","isHome":true,"opp_display":"Sevilla FC"},{"r":"D","gf":2,"ga":2,"opp":"Valencia CF","isHome":false,"opp_display":"Valencia CF"},{"r":"W","gf":4,"ga":0,"opp":"RC Celta de Vigo","isHome":true,"opp_display":"RC Celta"},{"r":"W","gf":4,"ga":2,"opp":"CA Osasuna","isHome":false,"opp_display":"CA Osasuna"},{"r":"W","gf":2,"ga":0,"opp":"Athletic Club","isHome":true,"opp_display":"Athletic Club"},{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":false,"opp_display":"RCD Mallorca"},{"r":"W","gf":3,"ga":2,"opp":"FC Barcelona","isHome":true,"opp_display":"FC Barcelona"},{"r":"W","gf":1,"ga":0,"opp":"Real Sociedad de Fútbol","isHome":false,"opp_display":"Real Sociedad"},{"r":"W","gf":3,"ga":0,"opp":"Cádiz CF","isHome":true,"opp_display":"Cádiz CF"},{"r":"W","gf":4,"ga":0,"opp":"Granada CF","isHome":false,"opp_display":"Granada CF"},{"r":"W","gf":5,"ga":0,"opp":"Deportivo Alavés","isHome":true,"opp_display":"Deportivo Alavés"},{"r":"D","gf":4,"ga":4,"opp":"Villarreal CF","isHome":false,"opp_display":"Villarreal CF"},{"r":"D","gf":0,"ga":0,"opp":"Real Betis Balompié","isHome":true,"opp_display":"Real Betis"}],"display_name":"Real Madrid","pts_per_game":2.5,"gf_per_game":2.29,"ga_per_game":0.68,"splits":{"away":{"team":"Real Madrid CF","side":"away","played":19,"won":"13","drew":"5","lost":"1","gf":"39","ga":"17"},"home":{"team":"Real Madrid CF","side":"home","played":19,"won":"16","drew":"3","lost":"0","gf":"48","ga":"9"}},"home_win_pct":84.2,"away_win_pct":68.4},{"team":"FC Barcelona","played":38,"pts":"85","won":"26","drew":"7","lost":"5","gf":"79","ga":"44","gd":"35","form":["L","W","W","W","W"],"form_detail":[{"r":"W","gf":2,"ga":1,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":4,"ga":2,"opp":"Real Betis Balompié","isHome":false,"opp_display":"Real Betis"},{"r":"L","gf":3,"ga":5,"opp":"Villarreal CF","isHome":true,"opp_display":"Villarreal CF"},{"r":"W","gf":1,"ga":0,"opp":"CA Osasuna","isHome":true,"opp_display":"CA Osasuna"},{"r":"W","gf":3,"ga":1,"opp":"Deportivo Alavés","isHome":false,"opp_display":"Deportivo Alavés"},{"r":"D","gf":3,"ga":3,"opp":"Granada CF","isHome":tru

In [190]:
scripts1 = soup_liga1.find_all("script")

print(len(scripts1))

for script1 in scripts1:

    if "Barcelona" in script1.get_text():

        print(script1.get_text()[:3000])


scripts2 = soup_liga2.find_all("script")

print(len(scripts2))

for script2 in scripts2:

    if "Barcelona" in script2.get_text():

        print(script2.get_text()[:3000])

19
{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"La Liga 2024/2025: ¿quién lidera la clasificación?","acceptedAnswer":{"@type":"Answer","text":"Líder: FC Barcelona, con 88 puntos en 38 partidos (2,32 puntos por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿qué equipo tiene el mejor ataque?","acceptedAnswer":{"@type":"Answer","text":"Mejor ataque: FC Barcelona, con 102 goles marcados (2,68 goles por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿qué equipo tiene la mejor defensa?","acceptedAnswer":{"@type":"Answer","text":"Mejor defensa: Athletic Club, con 29 goles encajados (0,76 goles por partido)."}},{"@type":"Question","name":"La Liga 2024/2025: ¿cuántas jornadas se han disputado?","acceptedAnswer":{"@type":"Answer","text":"Se han disputado 38 jornadas esta temporada."}}]}

window.standingsData   = [{"team":"FC Barcelona","played":38,"pts":"88","won":"28","drew":"4","lost":"6","gf":"102","ga":"39","gd":"63","form":["W","W","W","L","W"],"form_detail":[{"r":"L","gf":1,"ga":2,"opp":"Club Atlético de Madrid","isHome":true,"opp_display":"Atlético de Madrid"},{"r":"D","gf":1,"ga":1,"opp":"Getafe CF","isHome":false,"opp_display":"Getafe CF"},{"r":"W","gf":7,"ga":1,"opp":"Valencia CF","isHome":true,"opp_display":"Valencia CF"},{"r":"W","gf":1,"ga":0,"opp":"Deportivo Alavés","isHome":true,"opp_display":"Deportivo Alavés"},{"r":"W","gf":4,"ga":1,"opp":"Sevilla FC","isHome":false,"opp_display":"Sevilla FC"},{"r":"W","gf":1,"ga":0,"opp":"Rayo Vallecano de Madrid","isHome":true,"opp_display":"Rayo Vallecano"},{"r":"W","gf":2,"ga":0,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":4,"ga":0,"opp":"Real Sociedad de Fútbol","isHome":true,"opp_display":"Real Sociedad"},{"r":"W","gf":4,"ga":2,"opp":"Club Atlético de Madrid","isHome":false,"opp_display":"Atlético de Madrid"},{"r":"W","gf":3,"ga":0,"opp":"CA Osasuna","isHome":true,"opp_display":"CA Osasuna"},{"r":"W","gf":4,"ga":1,"opp":"Girona FC","isHome":true,"opp_display":"Girona FC"},{"r":"D","gf":1,"ga":1,"opp":"Real Betis Balompié","isHome":true,"opp_display":"Real Betis"},{"r":"W","gf":1,"ga":0,"opp":"CD Leganés","isHome":false,"opp_display":"CD Leganés"},{"r":"W","gf":4,"ga":3,"opp":"RC Celta de Vigo","isHome":true,"opp_display":"RC Celta"},{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":true,"opp_display":"RCD Mallorca"},{"r":"W","gf":2,"ga":1,"opp":"Real Valladolid CF","isHome":false,"opp_display":"Real Valladolid CF"},{"r":"W","gf":4,"ga":3,"opp":"Real Madrid CF","isHome":true,"opp_display":"Real Madrid"},{"r":"W","gf":2,"ga":0,"opp":"RCD Espanyol de Barcelona","isHome":false,"opp_display":"RCD Espanyol"},{"r":"L","gf":2,"ga":3,"opp":"Villarreal CF","isHome":true,"opp_display":"Villarreal CF"},{"r":"W","gf":3,"ga":0,"opp":"Athletic Club","isHome":false,"opp_display":"Athletic Club"}],"display_name":"FC Barcelona","pts_per_game":2.32,"gf_per_game":2.68,"ga_per_game":1.03,"splits":{"away":{"team":"FC Barcelona","side":"away","played":19,"won":"14","drew":"3","lost":"2","gf":"50","ga":"19"},"home":{"team":"FC Barcelona","side":"home","played":19,"won":"14","drew":"1","lost":"4","gf":"52","ga":"20"}},"home_win_pct":73.7,"away_win_pct":73.7},{"team":"Real Madrid CF","played":38,"pts":"84","won":"26","drew":"6","lost":"6","gf":"78","ga":"38","gd":"40","form":["W","L","W","W","W"],"form_detail":[{"r":"W","gf":2,"ga":1,"opp":"Valencia CF","isHome":false,"opp_display":"Valencia CF"},{"r":"W","gf":4,"ga":1,"opp":"UD Las Palmas","isHome":true,"opp_display":"UD Las Palmas"},{"r":"W","gf":3,"ga":0,"opp":"Real Valladolid CF","isHome":false,"opp_display":"Real Valladolid CF"},{"r":"L","gf":0,"ga":1,"opp":"RCD Espanyol de Barcelona","isHome":false,"opp_display":"RCD Espanyol"},{"r":"D","gf":1,"ga":1,"opp":"Club Atlético de Madrid","isHome":true,"opp_di
19

window.standingsData   = [{"team":"Real Madrid CF","played":38,"pts":"95","won":"29","drew":"8","lost":"1","gf":"87","ga":"26","gd":"61","form":["W","W","W","D","D"],"form_detail":[{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":true,"opp_display":"RCD Mallorca"},{"r":"W","gf":3,"ga":2,"opp":"UD Almería","isHome":true,"opp_display":"UD Almería"},{"r":"W","gf":2,"ga":1,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":2,"ga":0,"opp":"Getafe CF","isHome":false,"opp_display":"Getafe CF"},{"r":"D","gf":1,"ga":1,"opp":"Club Atlético de Madrid","isHome":true,"opp_display":"Atlético de Madrid"},{"r":"W","gf":4,"ga":0,"opp":"Girona FC","isHome":true,"opp_display":"Girona FC"},{"r":"D","gf":1,"ga":1,"opp":"Rayo Vallecano de Madrid","isHome":false,"opp_display":"Rayo Vallecano"},{"r":"W","gf":1,"ga":0,"opp":"Sevilla FC","isHome":true,"opp_display":"Sevilla FC"},{"r":"D","gf":2,"ga":2,"opp":"Valencia CF","isHome":false,"opp_display":"Valencia CF"},{"r":"W","gf":4,"ga":0,"opp":"RC Celta de Vigo","isHome":true,"opp_display":"RC Celta"},{"r":"W","gf":4,"ga":2,"opp":"CA Osasuna","isHome":false,"opp_display":"CA Osasuna"},{"r":"W","gf":2,"ga":0,"opp":"Athletic Club","isHome":true,"opp_display":"Athletic Club"},{"r":"W","gf":1,"ga":0,"opp":"RCD Mallorca","isHome":false,"opp_display":"RCD Mallorca"},{"r":"W","gf":3,"ga":2,"opp":"FC Barcelona","isHome":true,"opp_display":"FC Barcelona"},{"r":"W","gf":1,"ga":0,"opp":"Real Sociedad de Fútbol","isHome":false,"opp_display":"Real Sociedad"},{"r":"W","gf":3,"ga":0,"opp":"Cádiz CF","isHome":true,"opp_display":"Cádiz CF"},{"r":"W","gf":4,"ga":0,"opp":"Granada CF","isHome":false,"opp_display":"Granada CF"},{"r":"W","gf":5,"ga":0,"opp":"Deportivo Alavés","isHome":true,"opp_display":"Deportivo Alavés"},{"r":"D","gf":4,"ga":4,"opp":"Villarreal CF","isHome":false,"opp_display":"Villarreal CF"},{"r":"D","gf":0,"ga":0,"opp":"Real Betis Balompié","isHome":true,"opp_display":"Real Betis"}],"display_name":"Real Madrid","pts_per_game":2.5,"gf_per_game":2.29,"ga_per_game":0.68,"splits":{"away":{"team":"Real Madrid CF","side":"away","played":19,"won":"13","drew":"5","lost":"1","gf":"39","ga":"17"},"home":{"team":"Real Madrid CF","side":"home","played":19,"won":"16","drew":"3","lost":"0","gf":"48","ga":"9"}},"home_win_pct":84.2,"away_win_pct":68.4},{"team":"FC Barcelona","played":38,"pts":"85","won":"26","drew":"7","lost":"5","gf":"79","ga":"44","gd":"35","form":["L","W","W","W","W"],"form_detail":[{"r":"W","gf":2,"ga":1,"opp":"UD Las Palmas","isHome":false,"opp_display":"UD Las Palmas"},{"r":"W","gf":4,"ga":2,"opp":"Real Betis Balompié","isHome":false,"opp_display":"Real Betis"},{"r":"L","gf":3,"ga":5,"opp":"Villarreal CF","isHome":true,"opp_display":"Villarreal CF"},{"r":"W","gf":1,"ga":0,"opp":"CA Osasuna","isHome":true,"opp_display":"CA Osasuna"},{"r":"W","gf":3,"ga":1,"opp":"Deportivo Alavés","isHome":false,"opp_display":"Deportivo Alavés"},{"r":"D","gf":3,"ga":3,"opp":"Granada CF","isHome":tru

In [191]:
for script1 in soup1.find_all("script"):
    texto1 = script1.get_text()

    if "rankingData" in texto1:
        print(texto1[:1000])

window.pageLocale = 'es-ES';
window.rankingData       = [{"team":"Paris Saint-Germain FC","league":"FL1","played":34,"pts":84,"won":26,"drew":6,"lost":2,"gf":92,"ga":35,"gd":57,"pts_per_game":2.471,"gf_per_game":2.706,"ga_per_game":1.029,"unbeaten_pct":94.1,"win_pct":76.5,"draw_pct":17.6,"loss_pct":5.9,"gd_per_game":1.68,"home_won":14,"home_drew":2,"home_lost":1,"away_won":12,"away_drew":4,"away_lost":1,"home_win_pct":82.4,"away_win_pct":70.6,"home_gf":45,"home_ga":16,"home_played":17,"home_gf_per_game":2.647,"home_ga_per_game":0.941,"away_gf":47,"away_ga":19,"away_played":17,"away_gf_per_game":2.765,"away_ga_per_game":1.118,"form":["D","L","L","W","W"],"form_detail":[{"r":"W","gf":5,"ga":2,"opp":"Stade Brestois 29","isHome":false,"opp_display":"Brest"},{"r":"W","gf":4,"ga":1,"opp":"AS Monaco FC","isHome":true,"opp_display":"Mónaco"},{"r":"W","gf":1,"ga":0,"opp":"Toulouse FC","isHome":false,"opp_display":"Toulouse"},{"r":"W","gf":3,"ga":2,"opp":"Olympique Lyonnais","isHome":false,"opp

(function(){

    var leagueColors = { PL:'#38003c', FL1:'#003e7e', PD:'#ee8707', BL1:'#d00027', SA:'#024494' };

    function escHtml(s){
        return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    // Formatte un nombre décimal selon la locale de la page (séparateur décimal adapté)
    function fmtNum(v, decimals) {
        return v.toLocaleString(window.pageLocale || 'fr-FR', {
            minimumFractionDigits: decimals,
            maximumFractionDigits: decimals
        });
    }

    // Rangée « barre de classement » : la barre de fond encode la valeur relative
    function rankBarHtml(t, i, pct, valHtml) {
        var abbr = window.leagueAbbr[t.league] || t.league;
        return '<li class="rank-bar" style="--pct:' + Math.max(pct, 3) + '%;">'
            + '<span class="rank-bar-pos">' + (i + 1) + '</span>'
            + '<span class="rank-bar-name">' + escHtml(t.display_name||t.team)
            + '<span class="l

In [192]:
for script2 in soup2.find_all("script"):
    texto2 = script2.get_text()

    if "rankingData2" in texto2:
        print(texto2[:1000])

In [193]:
import json

for script1 in soup1.find_all("script"):
    texto1 = script1.get_text()

    if "window.rankingData" in texto1:
        datos1 = texto1.split("window.rankingData", 1)[1]
        datos1 = datos1.split("=", 1)[1]
        datos1 = datos1.split(";", 1)[0].strip()

        standings1 = json.loads(datos1)

        break

print(standings1[0])
print(len(standings1))

{'team': 'Paris Saint-Germain FC', 'league': 'FL1', 'played': 34, 'pts': 84, 'won': 26, 'drew': 6, 'lost': 2, 'gf': 92, 'ga': 35, 'gd': 57, 'pts_per_game': 2.471, 'gf_per_game': 2.706, 'ga_per_game': 1.029, 'unbeaten_pct': 94.1, 'win_pct': 76.5, 'draw_pct': 17.6, 'loss_pct': 5.9, 'gd_per_game': 1.68, 'home_won': 14, 'home_drew': 2, 'home_lost': 1, 'away_won': 12, 'away_drew': 4, 'away_lost': 1, 'home_win_pct': 82.4, 'away_win_pct': 70.6, 'home_gf': 45, 'home_ga': 16, 'home_played': 17, 'home_gf_per_game': 2.647, 'home_ga_per_game': 0.941, 'away_gf': 47, 'away_ga': 19, 'away_played': 17, 'away_gf_per_game': 2.765, 'away_ga_per_game': 1.118, 'form': ['D', 'L', 'L', 'W', 'W'], 'form_detail': [{'r': 'W', 'gf': 5, 'ga': 2, 'opp': 'Stade Brestois 29', 'isHome': False, 'opp_display': 'Brest'}, {'r': 'W', 'gf': 4, 'ga': 1, 'opp': 'AS Monaco FC', 'isHome': True, 'opp_display': 'Mónaco'}, {'r': 'W', 'gf': 1, 'ga': 0, 'opp': 'Toulouse FC', 'isHome': False, 'opp_display': 'Toulouse'}, {'r': 'W', 'gf': 3, 'ga': 2, 'opp': 'Olympique Lyonnais', 'isHome': False, 'opp_display': 'Olympique de Lyon'}, {'r': 'W', 'gf': 4, 'ga': 1, 'opp': 'Lille OSC', 'isHome': True, 'opp_display': 'Lille'}, {'r': 'W', 'gf': 4, 'ga': 1, 'opp': 'Stade Rennais FC 1901', 'isHome': False, 'opp_display': 'Stade Rennais'}, {'r': 'W', 'gf': 3, 'ga': 1, 'opp': 'Olympique de Marseille', 'isHome': True, 'opp_display': 'Olympique de Marsella'}, {'r': 'W', 'gf': 6, 'ga': 1, 'opp': 'AS Saint-Étienne', 'isHome': False, 'opp_display': 'Saint-Etienne'}, {'r': 'W', 'gf': 1, 'ga': 0, 'opp': 'Angers SCO', 'isHome': True, 'opp_display': 'Angers SCO'}, {'r': 'W', 'gf': 2, 'ga': 1, 'opp': 'Le Havre AC', 'isHome': True, 'opp_display': 'Le Havre'}, {'r': 'D', 'gf': 1, 'ga': 1, 'opp': 'FC Nantes', 'isHome': False, 'opp_display': 'Nantes'}, {'r': 'L', 'gf': 1, 'ga': 3, 'opp': 'OGC Nice', 'isHome': True, 'opp_display': 'Niza'}, {'r': 'L', 'gf': 1, 'ga': 2, 'opp': 'RC Strasbourg Alsace', 'isHome': False, 'opp_display': 'Racing Estrasburgo'}, {'r': 'W', 'gf': 4, 'ga': 1, 'opp': 'Montpellier HSC', 'isHome': False, 'opp_display': 'Montpellier'}, {'r': 'W', 'gf': 3, 'ga': 1, 'opp': 'AJ Auxerre', 'isHome': True, 'opp_display': 'Auxerre'}], 'streak': {'type': 'D', 'count': 1}, 'home_form': ['W', 'W', 'W', 'L', 'W'], 'away_form': ['W', 'W', 'D', 'L', 'W'], 'home_streak': {'type': 'W', 'count': 3}, 'away_streak': {'type': 'W', 'count': 2}, 'display_name': 'París Saint-Germain', 'club_url': '/es/Deporte/Futbol/Clubs/Palmares_Paris_Saint-Germain.php'}
96

In [194]:
import json

for script2 in soup2.find_all("script"):
    texto2 = script2.get_text()

    if "rankingData" in texto2:
        datos2 = texto2.split("rankingData", 1)[1]
        datos2 = datos2.split("=", 1)[1]
        datos2 = datos2.split(";", 1)[0].strip()

        standings2 = json.loads(datos2)

        break

print(standings2[0])
print(len(standings2))

{'team': 'Bayer 04 Leverkusen', 'league': 'BL1', 'played': 34, 'pts': 90, 'won': 28, 'drew': 6, 'lost': 0, 'gf': 89, 'ga': 24, 'gd': 65, 'pts_per_game': 2.647, 'gf_per_game': 2.618, 'ga_per_game': 0.706, 'unbeaten_pct': 100, 'win_pct': 82.4, 'draw_pct': 17.6, 'loss_pct': 0, 'gd_per_game': 1.91, 'home_won': 14, 'home_drew': 3, 'home_lost': 0, 'away_won': 14, 'away_drew': 3, 'away_lost': 0, 'home_win_pct': 82.4, 'away_win_pct': 82.4, 'home_gf': 47, 'home_ga': 11, 'home_played': 17, 'home_gf_per_game': 2.765, 'home_ga_per_game': 0.647, 'away_gf': 42, 'away_ga': 13, 'away_played': 17, 'away_gf_per_game': 2.471, 'away_ga_per_game': 0.765, 'form': ['D', 'D', 'W', 'W', 'W'], 'form_detail': [{'r': 'W', 'gf': 2, 'ga': 0, 'opp': 'SV Darmstadt 98', 'isHome': False, 'opp_display': 'SV Darmstadt 98'}, {'r': 'W', 'gf': 3, 'ga': 0, 'opp': 'FC Bayern München', 'isHome': True, 'opp_display': 'Bayern de Múnich'}, {'r': 'W', 'gf': 2, 'ga': 1, 'opp': '1. FC Heidenheim 1846', 'isHome': False, 'opp_display': '1. FC Heidenheim 1846'}, {'r': 'W', 'gf': 2, 'ga': 1, 'opp': '1. FSV Mainz 05', 'isHome': True, 'opp_display': 'Maguncia 05'}, {'r': 'W', 'gf': 2, 'ga': 0, 'opp': '1. FC Köln', 'isHome': False, 'opp_display': 'FC Colonia'}, {'r': 'W', 'gf': 2, 'ga': 0, 'opp': 'VfL Wolfsburg', 'isHome': True, 'opp_display': 'VfL Wolfsburgo'}, {'r': 'W', 'gf': 3, 'ga': 2, 'opp': 'SC Freiburg', 'isHome': False, 'opp_display': 'SC Friburgo'}, {'r': 'W', 'gf': 2, 'ga': 1, 'opp': 'TSG 1899 Hoffenheim', 'isHome': True, 'opp_display': 'Hoffenheim'}, {'r': 'W', 'gf': 1, 'ga': 0, 'opp': '1. FC Union Berlin', 'isHome': False, 'opp_display': '1. FC Union Berlin'}, {'r': 'W', 'gf': 5, 'ga': 0, 'opp': 'SV Werder Bremen', 'isHome': True, 'opp_display': 'Werder Bremen'}, {'r': 'D', 'gf': 1, 'ga': 1, 'opp': 'Borussia Dortmund', 'isHome': False, 'opp_display': 'Borussia Dortmund'}, {'r': 'D', 'gf': 2, 'ga': 2, 'opp': 'VfB Stuttgart', 'isHome': True, 'opp_display': 'VfB Stuttgart'}, {'r': 'W', 'gf': 5, 'ga': 1, 'opp': 'Eintracht Frankfurt', 'isHome': False, 'opp_display': 'Eintracht Fráncfort'}, {'r': 'W', 'gf': 5, 'ga': 0, 'opp': 'VfL Bochum 1848', 'isHome': False, 'opp_display': 'VfL Bochum'}, {'r': 'W', 'gf': 2, 'ga': 1, 'opp': 'FC Augsburg', 'isHome': True, 'opp_display': 'FC Augsburgo'}], 'streak': {'type': 'D', 'count': 2}, 'home_form': ['W', 'W', 'W', 'D', 'W'], 'away_form': ['W', 'W', 'D', 'W', 'W'], 'home_streak': {'type': 'W', 'count': 3}, 'away_streak': {'type': 'W', 'count': 2}, 'display_name': 'Bayer Leverkusen', 'club_url': '/es/Deporte/Futbol/Clubs/Palmares_Bayer_Leverkusen.php'}
96

In [195]:
datos_liga1 = []

for equipo1 in standings1:

    datos_liga1.append([
        equipo1["league"],
        equipo1["team"],
        equipo1["pts"],
        equipo1["gf"],
        equipo1["ga"],
    ])

print(datos_liga1)

[['FL1', 'Paris Saint-Germain FC', 84, 92, 35], ['BL1', 'FC Bayern München', 82, 99, 32], ['PD', 'FC Barcelona', 88, 102, 39], ['PL', 'Liverpool FC', 84, 86, 41], ['PD', 'Real Madrid CF', 84, 78, 38], ['SA', 'SSC Napoli', 82, 59, 27], ['SA', 'FC Internazionale Milano', 81, 79, 35], ['BL1', 'Bayer 04 Leverkusen', 69, 72, 43], ['PD', 'Club Atlético de Madrid', 76, 68, 30], ['SA', 'Atalanta BC', 74, 78, 37], ['PL', 'Arsenal FC', 74, 69, 34], ['FL1', 'Olympique de Marseille', 65, 74, 47], ['PL', 'Manchester City FC', 71, 72, 44], ['PD', 'Athletic Club', 70, 54, 29], ['SA', 'Juventus FC', 70, 58, 35], ['PD', 'Villarreal CF', 70, 71, 51], ['PL', 'Chelsea FC', 69, 64, 43], ['SA', 'AS Roma', 69, 56, 35], ['FL1', 'AS Monaco FC', 61, 63, 41], ['FL1', 'OGC Nice', 60, 66, 41], ['BL1', 'Eintracht Frankfurt', 60, 68, 46], ['FL1', 'Lille OSC', 60, 52, 36], ['PL', 'Newcastle United FC', 66, 68, 47], ['PL', 'Aston Villa FC', 66, 58, 51], ['SA', 'ACF Fiorentina', 65, 60, 41], ['PL', 'Nottingham Forest FC', 65, 58, 46], ['SA', 'SS Lazio', 65, 61, 49], ['BL1', 'Borussia Dortmund', 57, 71, 51], ['FL1', 'Olympique Lyonnais', 57, 65, 46], ['FL1', 'RC Strasbourg Alsace', 57, 56, 44], ['SA', 'AC Milan', 63, 61, 43], ['SA', 'Bologna FC 1909', 62, 57, 47], ['BL1', 'SC Freiburg', 55, 49, 53], ['PL', 'Brighton & Hove Albion FC', 61, 66, 59], ['PD', 'Real Betis Balompié', 60, 57, 50], ['BL1', '1. FSV Mainz 05', 52, 55, 43], ['FL1', 'Racing Club de Lens', 52, 42, 39], ['BL1', 'RB Leipzig', 51, 53, 48], ['BL1', 'SV Werder Bremen', 51, 54, 57], ['PL', 'AFC Bournemouth', 56, 58, 46], ['PL', 'Brentford FC', 56, 66, 57], ['BL1', 'VfB Stuttgart', 50, 64, 53], ['FL1', 'Stade Brestois 29', 50, 52, 59], ['PD', 'RC Celta de Vigo', 55, 59, 57], ['PL', 'Fulham FC', 54, 54, 54], ['PL', 'Crystal Palace FC', 53, 51, 51], ['PD', 'CA Osasuna', 52, 48, 52], ['PD', 'Rayo Vallecano de Madrid', 52, 41, 45], ['BL1', 'Borussia Mönchengladbach', 45, 55, 57], ['SA', 'Como 1907', 49, 49, 52], ['BL1', 'VfL Wolfsburg', 43, 56, 54], ['BL1', 'FC Augsburg', 43, 35, 51], ['PL', 'Everton FC', 48, 42, 44], ['PD', 'RCD Mallorca', 48, 35, 44], ['FL1', 'Toulouse FC', 42, 44, 43], ['FL1', 'AJ Auxerre', 42, 48, 51], ['BL1', '1. FC Union Berlin', 40, 35, 49], ['PD', 'Valencia CF', 46, 44, 54], ['PD', 'Real Sociedad de Fútbol', 46, 35, 46], ['FL1', 'Stade Rennais FC 1901', 41, 51, 50], ['SA', 'Torino FC', 44, 39, 45], ['SA', 'Udinese Calcio', 44, 41, 56], ['SA', 'Genoa CFC', 43, 37, 49], ['PL', 'West Ham United FC', 43, 46, 62], ['PD', 'Getafe CF', 42, 34, 39], ['PL', 'Manchester United FC', 42, 44, 54], ['PD', 'Deportivo Alavés', 42, 38, 48], ['PD', 'RCD Espanyol de Barcelona', 42, 40, 51], ['PL', 'Wolverhampton Wanderers FC', 42, 54, 69], ['PD', 'Sevilla FC', 41, 42, 55], ['PD', 'Girona FC', 41, 44, 60], ['FL1', 'FC Nantes', 36, 39, 52], ['FL1', 'Angers SCO', 36, 32, 53], ['PD', 'CD Leganés', 40, 39, 56], ['PL', 'Tottenham Hotspur FC', 38, 64, 65], ['FL1', 'Le Havre AC', 34, 40, 71], ['SA', 'Hellas Verona FC', 37, 34, 66], ['FL1', 'Stade de Reims', 33, 33, 47], ['SA', 'Parma Calcio 1913', 36, 44, 58], ['SA', 'Cagliari Calcio', 36, 40, 56], ['BL1', 'FC St. Pauli 1910', 32, 28, 41], ['BL1', 'TSG 1899 Hoffenheim', 32, 46, 68], ['SA', 'US Lecce', 34, 27, 58], ['BL1', '1. FC Heidenheim 1846', 29, 37, 64], ['PD', 'UD Las Palmas', 32, 40, 61], ['FL1', 'AS Saint-Étienne', 27, 37, 77], ['SA', 'Empoli FC', 31, 33, 59], ['SA', 'Venezia FC', 29, 32, 56], ['BL1', 'Holstein Kiel', 25, 49, 80], ['BL1', 'VfL Bochum 1848', 22, 31, 67], ['PL', 'Leicester City FC', 25, 33, 80], ['PL', 'Ipswich Town FC', 22, 36, 82], ['FL1', 'Montpellier HSC', 16, 23, 77], ['SA', 'AC Monza', 18, 28, 69], ['PD', 'Real Valladolid CF', 16, 26, 90], ['PL', 'Southampton FC', 12, 26, 86]]

In [196]:
datos_liga2 = []

for equipo2 in standings2:
    datos_liga2.append([
        equipo2["league"],
        equipo2["team"],
        equipo2["pts"],
        equipo2["gf"],
        equipo2["ga"]
    ])

print(datos_liga2)

[['BL1', 'Bayer 04 Leverkusen', 90, 89, 24], ['PD', 'Real Madrid CF', 95, 87, 26], ['SA', 'FC Internazionale Milano', 94, 89, 22], ['PL', 'Manchester City FC', 91, 96, 34], ['PL', 'Arsenal FC', 89, 91, 29], ['PD', 'FC Barcelona', 85, 79, 44], ['FL1', 'Paris Saint-Germain FC', 76, 81, 33], ['PL', 'Liverpool FC', 82, 86, 41], ['BL1', 'VfB Stuttgart', 73, 78, 39], ['PD', 'Girona FC', 81, 85, 46], ['BL1', 'FC Bayern München', 72, 94, 45], ['PD', 'Club Atlético de Madrid', 76, 70, 43], ['SA', 'AC Milan', 75, 76, 49], ['FL1', 'AS Monaco FC', 67, 68, 42], ['BL1', 'RB Leipzig', 65, 77, 39], ['SA', 'Juventus FC', 71, 54, 31], ['BL1', 'Borussia Dortmund', 63, 68, 43], ['SA', 'Atalanta BC', 69, 72, 42], ['FL1', 'Stade Brestois 29', 61, 53, 34], ['PD', 'Athletic Club', 68, 61, 37], ['SA', 'Bologna FC 1909', 68, 54, 32], ['PL', 'Aston Villa FC', 68, 76, 61], ['PL', 'Tottenham Hotspur FC', 66, 74, 61], ['FL1', 'Lille OSC', 59, 52, 34], ['SA', 'AS Roma', 63, 65, 46], ['PL', 'Chelsea FC', 63, 77, 63], ['FL1', 'OGC Nice', 55, 40, 29], ['SA', 'SS Lazio', 61, 49, 39], ['PL', 'Newcastle United FC', 60, 85, 62], ['SA', 'ACF Fiorentina', 60, 61, 46], ['PD', 'Real Sociedad de Fútbol', 60, 51, 39], ['PL', 'Manchester United FC', 60, 57, 58], ['FL1', 'Olympique Lyonnais', 53, 49, 55], ['FL1', 'Racing Club de Lens', 51, 45, 37], ['PD', 'Real Betis Balompié', 57, 48, 45], ['FL1', 'Olympique de Marseille', 50, 52, 41], ['SA', 'SSC Napoli', 53, 55, 48], ['PD', 'Villarreal CF', 53, 65, 65], ['SA', 'Torino FC', 53, 36, 36], ['BL1', 'Eintracht Frankfurt', 47, 51, 50], ['FL1', 'Stade de Reims', 47, 42, 47], ['PL', 'West Ham United FC', 52, 60, 74], ['FL1', 'Stade Rennais FC 1901', 46, 53, 46], ['BL1', 'TSG 1899 Hoffenheim', 46, 66, 66], ['SA', 'Genoa CFC', 49, 45, 45], ['PL', 'Crystal Palace FC', 49, 57, 58], ['PD', 'Valencia CF', 49, 40, 45], ['FL1', 'Toulouse FC', 43, 42, 46], ['PL', 'Brighton & Hove Albion FC', 48, 55, 62], ['PL', 'Everton FC', 48, 40, 51], ['PL', 'AFC Bournemouth', 48, 54, 67], ['PL', 'Fulham FC', 47, 55, 61], ['FL1', 'Montpellier HSC', 42, 43, 48], ['BL1', '1. FC Heidenheim 1846', 42, 50, 55], ['BL1', 'SV Werder Bremen', 42, 48, 54], ['BL1', 'SC Freiburg', 42, 45, 58], ['PD', 'Deportivo Alavés', 46, 36, 46], ['PL', 'Wolverhampton Wanderers FC', 46, 50, 65], ['PD', 'CA Osasuna', 45, 45, 56], ['SA', 'AC Monza', 45, 39, 51], ['BL1', 'FC Augsburg', 39, 50, 60], ['FL1', 'RC Strasbourg Alsace', 39, 38, 50], ['PD', 'Getafe CF', 43, 42, 54], ['BL1', 'VfL Wolfsburg', 37, 41, 56], ['PD', 'Sevilla FC', 41, 48, 54], ['PD', 'RC Celta de Vigo', 41, 46, 57], ['PD', 'RCD Mallorca', 40, 33, 44], ['PD', 'UD Las Palmas', 40, 33, 47], ['BL1', '1. FSV Mainz 05', 35, 39, 51], ['PL', 'Brentford FC', 39, 56, 65], ['BL1', 'Borussia Mönchengladbach', 34, 56, 67], ['SA', 'Hellas Verona FC', 38, 38, 51], ['PD', 'Rayo Vallecano de Madrid', 38, 29, 48], ['SA', 'US Lecce', 38, 32, 54], ['SA', 'Udinese Calcio', 37, 37, 53], ['FL1', 'FC Nantes', 33, 30, 55], ['BL1', '1. FC Union Berlin', 33, 33, 58], ['BL1', 'VfL Bochum 1848', 33, 42, 74], ['PL', 'Nottingham Forest FC', 36, 49, 67], ['SA', 'Empoli FC', 36, 29, 54], ['SA', 'Cagliari Calcio', 36, 42, 68], ['FL1', 'Le Havre AC', 32, 34, 45], ['SA', 'Frosinone Calcio', 35, 44, 69], ['PD', 'Cádiz CF', 33, 26, 55], ['FL1', 'FC Lorient', 29, 43, 66], ['FL1', 'FC Metz', 29, 35, 58], ['BL1', '1. FC Köln', 27, 28, 60], ['SA', 'US Sassuolo Calcio', 30, 43, 75], ['FL1', 'Clermont Foot 63', 25, 26, 60], ['PL', 'Luton Town FC', 26, 52, 85], ['PL', 'Burnley FC', 24, 41, 78], ['PD', 'UD Almería', 21, 43, 75], ['PD', 'Granada CF', 21, 38, 79], ['BL1', 'SV Darmstadt 98', 17, 30, 86], ['SA', 'US Salernitana 1919', 17, 32, 81], ['PL', 'Sheffield United FC', 16, 35, 104]]

In [197]:
import pandas as pd

df1 = pd.DataFrame(
    datos_liga1,
    columns=["liga", "equipo", "puntos", "goles_favor", "goles_contra"]
)

df1

   liga                  equipo  puntos  goles_favor  goles_contra
0   FL1  Paris Saint-Germain FC      84           92            35
1   BL1       FC Bayern München      82           99            32
2    PD            FC Barcelona      88          102            39
3    PL            Liverpool FC      84           86            41
4    PD          Real Madrid CF      84           78            38
..  ...                     ...     ...          ...           ...
91   PL         Ipswich Town FC      22           36            82
92  FL1         Montpellier HSC      16           23            77
93   SA                AC Monza      18           28            69
94   PD      Real Valladolid CF      16           26            90
95   PL          Southampton FC      12           26            86

[96 rows x 5 columns]

In [198]:
import pandas as pd

df2 = pd.DataFrame(
    datos_liga2,
    columns=["liga", "equipo", "puntos", "goles_favor", "goles_contra"]
)
df2

   liga                    equipo  puntos  goles_favor  goles_contra
0   BL1       Bayer 04 Leverkusen      90           89            24
1    PD            Real Madrid CF      95           87            26
2    SA  FC Internazionale Milano      94           89            22
3    PL        Manchester City FC      91           96            34
4    PL                Arsenal FC      89           91            29
..  ...                       ...     ...          ...           ...
91   PD                UD Almería      21           43            75
92   PD                Granada CF      21           38            79
93  BL1           SV Darmstadt 98      17           30            86
94   SA       US Salernitana 1919      17           32            81
95   PL       Sheffield United FC      16           35           104

[96 rows x 5 columns]

In [199]:
df1["temporada"] = "2024-25"
df2["temporada"] = "2023-24"

In [246]:
df_final = pd.concat([df1, df2], ignore_index=True)

In [247]:
df_final

    liga                  equipo  puntos  goles_favor  goles_contra temporada
0    FL1  Paris Saint-Germain FC      84           92            35   2024-25
1    BL1       FC Bayern München      82           99            32   2024-25
2     PD            FC Barcelona      88          102            39   2024-25
3     PL            Liverpool FC      84           86            41   2024-25
4     PD          Real Madrid CF      84           78            38   2024-25
..   ...                     ...     ...          ...           ...       ...
187   PD              UD Almería      21           43            75   2023-24
188   PD              Granada CF      21           38            79   2023-24
189  BL1         SV Darmstadt 98      17           30            86   2023-24
190   SA     US Salernitana 1919      17           32            81   2023-24
191   PL     Sheffield United FC      16           35           104   2023-24

[192 rows x 6 columns]

AHORA SOLO QUIERO TRABAJAR CON LA COMBIANACIÓN DE DOS DATAFRAMES DF1 Y DF2. PARA IR TRABAJANDO MAS COMODAMENTE

In [201]:
df_final_Union_dos_temporadas = pd.concat([df1, df2], ignore_index=True)

ESTE ES MI DATA SET FINAL PARA OBTENER TODOS LOS EQUIPOS DE LAS 5 GRANDES LIGAS DE LAS TEMPORADAS 2023-24 Y 2024-2025

In [202]:
df_final_Union_dos_temporadas

    liga                  equipo  puntos  goles_favor  goles_contra temporada
0    FL1  Paris Saint-Germain FC      84           92            35   2024-25
1    BL1       FC Bayern München      82           99            32   2024-25
2     PD            FC Barcelona      88          102            39   2024-25
3     PL            Liverpool FC      84           86            41   2024-25
4     PD          Real Madrid CF      84           78            38   2024-25
..   ...                     ...     ...          ...           ...       ...
187   PD              UD Almería      21           43            75   2023-24
188   PD              Granada CF      21           38            79   2023-24
189  BL1         SV Darmstadt 98      17           30            86   2023-24
190   SA     US Salernitana 1919      17           32            81   2023-24
191   PL     Sheffield United FC      16           35           104   2023-24

[192 rows x 6 columns]

In [203]:
df_final_Union_dos_temporadas["liga"] = df_final_Union_dos_temporadas["liga"].replace({
    "FL1": "France Ligue 1 FRA",
    "BL1": "Bundesliga 1 ALE",
    "PD": "Primera División ESP",
    "PL": "Premier League ENG",
    "SA": "Serie A ITA"
})

In [204]:
df_final_Union_dos_temporadas

,liga,equipo,puntos,goles_favor,goles_contra,temporada
0,France Ligue 1 FRA,Paris Saint-Germain FC,84,92,35,2024-25
1,Bundesliga 1 ALE,FC Bayern München,82,99,32,2024-25
2,Primera División ESP,FC Barcelona,88,102,39,2024-25
3,Premier League ENG,Liverpool FC,84,86,41,2024-25
4,Primera División ESP,Real Madrid CF,84,78,38,2024-25
...,...,...,...,...,...,...
187,Primera División ESP,UD Almería,21,43,75,2023-24
188,Primera División ESP,Granada CF,21,38,79,2023-24
189,Bundesliga 1 ALE,SV Darmstadt 98,17,30,86,2023-24
190,Serie A ITA,US Salernitana 1919,17,32,81,2023-24
191,Premier League ENG,Sheffield United FC,16,35,104,2023-24

Ahora vamos a automatizar las 5 ligas de los 2 años y crear el DataFrame final.

ESTE ES OTRO METODO DE EXTRACCIÓN DE LOS URLS.

Si ya conozco las URLS de cada pagina cojo las 10 paginas que me interesan. Analizo cada URL y extraigo los datos. Pero eso no signifa que tenga los datos dentro de la página.

Esto hace que mi código sea mucho más sencillo y controlable.

In [205]:
import requests
import json
import pandas as pd

ligas = {
    "Premier League 2024-2025": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Premier-League-2024-2025.php",
    "Ligue 1 2024-2025": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Ligue-1-2024-2025.php",
    "La Liga 2024-2025": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/La-Liga-2024-2025.php",
    "Bundesliga 2024-2025": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Bundesliga-2024-2025.php",
    "Serie A 2024-2025": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Serie-A-2024-2025.php",
    "Premier League 2023-2024": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Premier-League-2023-2024.php",
    "Ligue 1 2023-2024": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Ligue-1-2023-2024.php",
    "La Liga 2023-2024": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/La-Liga-2023-2024.php",
    "Bundesliga 2023-2024": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Bundesliga-2023-2024.php",
    "Serie A 2023-2024": "https://www.sport-histoire.fr/es/Deporte/Futbol/Campeonatos/Serie-A-2023-2024.php"
}

datos = []

for liga, url_liga in ligas.items():

    response = requests.get(url_liga)
    soup_liga = BeautifulSoup(response.text, "html.parser")

    for script in soup_liga.find_all("script"):

        texto = script.get_text()

        if "window.standingsData" in texto:

            datos_json = texto.split("window.standingsData   = ")[1]
            datos_json = datos_json.split(";")[0]

            standings = json.loads(datos_json)

            for equipo in standings:
                datos.append([
                    liga,
                    equipo["team"],
                    equipo["pts"],
                    equipo["gf"],
                    equipo["ga"]
                ])

            break

df = pd.DataFrame(
    datos,
    columns=["liga", "equipo", "puntos", "goles_favor", "goles_contra"]
)

df.tail()

                  liga               equipo puntos goles_favor goles_contra
187  Serie A 2023-2024            Empoli FC     36          29           54
188  Serie A 2023-2024      Cagliari Calcio     36          42           68
189  Serie A 2023-2024     Frosinone Calcio     35          44           69
190  Serie A 2023-2024   US Sassuolo Calcio     30          43           75
191  Serie A 2023-2024  US Salernitana 1919     17          32           81

In [206]:
df.head(60)

,liga,equipo,puntos,goles_favor,goles_contra
0,Premier League 2024-2025,Liverpool FC,84,86,41
1,Premier League 2024-2025,Arsenal FC,74,69,34
2,Premier League 2024-2025,Manchester City FC,71,72,44
3,Premier League 2024-2025,Chelsea FC,69,64,43
4,Premier League 2024-2025,Newcastle United FC,66,68,47
5,Premier League 2024-2025,Aston Villa FC,66,58,51
6,Premier League 2024-2025,Nottingham Forest FC,65,58,46
7,Premier League 2024-2025,Brighton & Hove Albion FC,61,66,59
8,Premier League 2024-2025,AFC Bournemouth,56,58,46
9,Premier League 2024-2025,Brentford FC,56,66,57
10,Premier League 2024-2025,Fulham FC,54,54,54
11,Premier League 2024-2025,Crystal Palace FC,53,51,51
12,Premier League 2024-2025,Everton FC,48,42,44
13,Premier League 2024-2025,West Ham United FC,43,46,62
14,Premier League 2024-2025,Manchester United FC,42,44,54
15,Premier League 2024-2025,Wolverhampton Wanderers FC,42,54,69
16,Premier League 2024-2025,Tottenham Hotspur FC,38,64,65
17,Premier League 2024-2025,Leicester City FC,25,33,80
18,Premier League 2024-2025,Ipswich Town FC,22,36,82
19,Premier League 2024-2025,Southampton FC,12,26,86
20,Ligue 1 2024-2025,Paris Saint-Germain FC,84,92,35
21,Ligue 1 2024-2025,Olympique de Marseille,65,74,47
22,Ligue 1 2024-2025,AS Monaco FC,61,63,41
23,Ligue 1 2024-2025,OGC Nice,60,66,41
24,Ligue 1 2024-2025,Lille OSC,60,52,36
25,Ligue 1 2024-2025,Olympique Lyonnais,57,65,46
26,Ligue 1 2024-2025,RC Strasbourg Alsace,57,56,44
27,Ligue 1 2024-2025,Racing Club de Lens,52,42,39
28,Ligue 1 2024-2025,Stade Brestois 29,50,52,59
29,Ligue 1 2024-2025,Toulouse FC,42,44,43
30,Ligue 1 2024-2025,AJ Auxerre,42,48,51
31,Ligue 1 2024-2025,Stade Rennais FC 1901,41,51,50
32,Ligue 1 2024-2025,FC Nantes,36,39,52
33,Ligue 1 2024-2025,Angers SCO,36,32,53
34,Ligue 1 2024-2025,Le Havre AC,34,40,71
35,Ligue 1 2024-2025,Stade de Reims,33,33,47
36,Ligue 1 2024-2025,AS Saint-Étienne,27,37,77
37,Ligue 1 2024-2025,Montpellier HSC,16,23,77
38,La Liga 2024-2025,FC Barcelona,88,102,39
39,La Liga 2024-2025,Real Madrid CF,84,78,38
40,La Liga 2024-2025,Club Atlético de Madrid,76,68,30
41,La Liga 2024-2025,Athletic Club,70,54,29
42,La Liga 2024-2025,Villarreal CF,70,71,51
43,La Liga 2024-2025,Real Betis Balompié,60,57,50
44,La Liga 2024-2025,RC Celta de Vigo,55,59,57
45,La Liga 2024-2025,CA Osasuna,52,48,52
46,La Liga 2024-2025,Rayo Vallecano de Madrid,52,41,45
47,La Liga 2024-2025,RCD Mallorca,48,35,44
48,La Liga 2024-2025,Valencia CF,46,44,54
49,La Liga 2024-2025,Real Sociedad de Fútbol,46,35,46
50,La Liga 2024-2025,Getafe CF,42,34,39
51,La Liga 2024-2025,Deportivo Alavés,42,38,48
52,La Liga 2024-2025,RCD Espanyol de Barcelona,42,40,51
53,La Liga 2024-2025,Sevilla FC,41,42,55
54,La Liga 2024-2025,Girona FC,41,44,60
55,La Liga 2024-2025,CD Leganés,40,39,56
56,La Liga 2024-2025,UD Las Palmas,32,40,61
57,La Liga 2024-2025,Real Valladolid CF,16,26,90
58,Bundesliga 2024-2025,FC Bayern München,82,99,32
59,Bundesliga 2024-2025,Bayer 04 Leverkusen,69,72,43

AHORA EN RELACION A EUROPEAN_FOOTBALL_PLAYES.CSV NOS QUEDAMOS CON ["Player", "Pos", "Squad", "Comp", "MP", "Starts", "Min"]. 

Estas son las variables que necesitamos para carga de minutos, titularidades y clubes.


EN RELACION A INJURIES24_25.CSV NOS QUEDAMOS CON ["Season", "Injury", "Days", "Games missed",
 "player_name", "player_position", "club", "league"]

In [207]:
import pandas as pd

df_players = pd.read_csv("european_football_players.csv")

df_injuries = pd.read_csv("injuries24_25.csv")

In [208]:
print(df_players.shape)
print(df_injuries.shape)

(2854, 27)
(15603, 11)

In [209]:
print(df_players.head())
print(df_injuries.head())

   Rk             Player   Nation Pos        Squad                Comp   Age  \
0   1         Max Aarons  eng ENG  DF  Bournemouth  eng Premier League  24.0
1   2         Max Aarons  eng ENG  DF     Valencia          es La Liga  24.0
2   3     Rodrigo Abajas   es ESP  DF     Valencia          es La Liga  21.0
3   4     James Abankwah   ie IRL  DF      Udinese          it Serie A  20.0
4   5  Keyliane Abdallah   fr FRA  FW    Marseille          fr Ligue 1  18.0

     Born  MP  Starts  ...  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
0  2000.0   3       1  ...      0     0     0    0.0    0.0    0.0     0.0
1  2000.0   4       1  ...      0     2     0    0.0    0.0    0.0     0.0
2  2003.0   1       1  ...      0     1     0    0.0    0.0    0.0     0.0
3  2004.0   6       0  ...      0     1     0    0.0    0.0    0.0     0.0
4  2006.0   1       0  ...      0     0     0    0.0    0.0    0.0     0.0

   G+A-PK  Matches     -9999
0     0.0  Matches  774cf58b
1     0.0  Matches  774cf58b
2     0.0  Matches  69c99fce
3     0.0  Matches  4b7a9fcc
4     0.0  Matches  7310786d

[5 rows x 27 columns]
  Season                     Injury     Days  Games missed injury_from_parsed  \
0  20/21  Syndesmosis ligament tear  43 days             9          1/28/2021
1  20/21                Knee injury  37 days             6           3/7/2021
2  20/21               Corona virus  21 days             4          2/17/2021
3  20/21                     bruise   8 days             2          11/6/2020
4  20/21            Ligament injury  22 days             2          7/26/2020

  injury_until_parsed           player_name  player_age player_position  \
0           3/11/2021       Alexander Nübel          24      Goalkeeper
1           4/12/2021  Ron-Thorben Hoffmann          22      Goalkeeper
2            3/9/2021       Benjamin Pavard          25     Centre-Back
3          11/13/2020       Benjamin Pavard          25     Centre-Back
4           8/16/2020       Benjamin Pavard          25     Centre-Back

            club      league
0  Bayern Munich  Bundesliga
1  Bayern Munich  Bundesliga
2  Bayern Munich  Bundesliga
3  Bayern Munich  Bundesliga
4  Bayern Munich  Bundesliga

In [210]:
columnas_players = [
    "Player",
    "Pos",
    "Squad",
    "Comp",
    "MP",
    "Starts",
    "Min"
]

In [211]:
columnas_injuries = [
    "Season",
    "Injury",
    "Days",
    "Games missed",
    "player_name",
    "player_position",
    "club",
    "league"
]

In [212]:
df_injuries = df_injuries[df_injuries["Season"] == "24/25"]

In [213]:
print(df_injuries.shape)
print(df_injuries["Season"].value_counts())

(3279, 11)
Season
24/25    3279
Name: count, dtype: int64

In [214]:
#PARA DF_PLAYERS

df_players = df_players[
    ["Player", "Pos", "Squad", "Comp", "MP", "Starts", "Min"]
]

In [215]:
#PARA DF_INJURIES

df_injuries = df_injuries[
    ["Season", "Injury", "Days", "Games missed",
     "player_name", "player_position", "club", "league"]
]

In [216]:
print(df_players.head())
print(df_players.shape)

print(df_injuries.head())
print(df_injuries.shape)

              Player Pos        Squad                Comp  MP  Starts  Min
0         Max Aarons  DF  Bournemouth  eng Premier League   3       1   86
1         Max Aarons  DF     Valencia          es La Liga   4       1  120
2     Rodrigo Abajas  DF     Valencia          es La Liga   1       1   65
3     James Abankwah  DF      Udinese          it Serie A   6       0   88
4  Keyliane Abdallah  FW    Marseille          fr Ligue 1   1       0    3
(2854, 7)
     Season               Injury     Days  Games missed    player_name  \
3267  24/25    Torn muscle fiber  56 days            10   Manuel Neuer
3268  24/25         Rib fracture  26 days             4   Manuel Neuer
3269  24/25       Thigh problems   9 days             1   Manuel Neuer
3270  24/25      Kidney problems  55 days            13  Daniel Peretz
3271  24/25  Partial muscle tear  63 days             6  Daniel Peretz

     player_position           club      league
3267      Goalkeeper  Bayern Munich  Bundesliga
3268      Goalkeeper  Bayern Munich  Bundesliga
3269      Goalkeeper  Bayern Munich  Bundesliga
3270      Goalkeeper  Bayern Munich  Bundesliga
3271      Goalkeeper  Bayern Munich  Bundesliga
(3279, 8)

In [217]:
print(df_players["Player"].head(20))
print(df_injuries["player_name"].head(20))

0             Max Aarons
1             Max Aarons
2         Rodrigo Abajas
3         James Abankwah
4      Keyliane Abdallah
5       Yunis Abdelhamid
6          Himad Abdelli
7     Mohamed Abdelmonem
8               Ali Abdi
9        Saud Abdulhamid
10         Nabil Aberdin
11     Oliver Abildgaard
12        Matthis Abline
13                 Abner
14     Zakaria Aboukhlal
15           Abdel Abqar
16         Tammy Abraham
17         Tammy Abraham
18    Federico Accornero
19      Francesco Acerbi
Name: Player, dtype: str
3267       Manuel Neuer
3268       Manuel Neuer
3269       Manuel Neuer
3270      Daniel Peretz
3271      Daniel Peretz
3272       Sven Ulreich
3273    Dayot Upamecano
3274    Dayot Upamecano
3275    Dayot Upamecano
3276    Dayot Upamecano
3277    Dayot Upamecano
3278    Dayot Upamecano
3279        Min-jae Kim
3280        Min-jae Kim
3281       Jonathan Tah
3282         Hiroki Ito
3283         Hiroki Ito
3284         Hiroki Ito
3285          Eric Dier
3286          Eric Dier
Name: player_name, dtype: str

In [218]:
print(df_players["Squad"].unique())
print(df_injuries["club"].unique())

<ArrowStringArray>
[    'Bournemouth',        'Valencia',         'Udinese',       'Marseille',
   'Saint-Étienne',          'Angers',            'Nice',            'Roma',
          'Getafe',            'Como',          'Nantes',            'Lyon',
        'Toulouse',          'Alavés',           'Milan',           'Genoa',
           'Inter',         'Chelsea',     'Montpellier',         'Sevilla',
          'Torino',        'Freiburg',           'Reims',        'Dortmund',
        'Brighton',      'Leverkusen',      'Fiorentina',      'Real Betis',
        'Juventus',         'Bologna',        'St Pauli',          'Wolves',
  'Crystal Palace',            'Lens',   'Athletic Club',   'Werder Bremen',
        'Espanyol',     'Real Madrid',   'Real Sociedad',          'Rennes',
      'Valladolid',      'Celta Vigo',      'Nottingham',   'Hellas Verona',
       'Brentford',           'Brest', 'Manchester City',      'Villarreal',
          'Monaco',         'Auxerre',           'Monza',      'Hoffenheim',
           'Lille',     'Southampton',         'Everton',       'Liverpool',
          'Girona',       'Newcastle',           'Parma',         'Venezia',
         'Leganés',  'Leicester City',        'West Ham', 'Atlético Madrid',
  'Manchester Utd',       'Frankfurt',        'Mainz 05',      'Strasbourg',
       'Wolfsburg',          'Fulham',          'Napoli',          'Empoli',
       'Barcelona',         'Osasuna',   'Holstein Kiel',        'Mallorca',
     'Aston Villa',        'Paris SG',        'Cagliari',       'Tottenham',
        'Le Havre',   'Bayern Munich',          'Bochum',      'Las Palmas',
        'Atalanta',      'RB Leipzig',  'Rayo Vallecano',           'Lecce',
        'Augsburg',      'Heidenheim',           'Lazio',    'Union Berlin',
       'Stuttgart',    'Ipswich Town',         'Arsenal',        'Gladbach']
Length: 96, dtype: str
<ArrowStringArray>
[           'Bayern Munich',        'Borussia Dortmund',
               'RB Leipzig',         'Bayer Leverkusen',
      'Eintracht Frankfurt',             'Union Berlin',
              'SC Freiburg',            'VfB Stuttgart',
            'Werder Bremen', 'Borussia Monchengladbach',
                 'Mainz 05',            'VfL Wolfsburg',
                 'Augsburg',               'Hoffenheim',
            'FC Heidenheim',             'FC St. Pauli',
            'Holstein Kiel',               'VfL Bochum',
                  'Arsenal',              'Aston Villa',
              'Bournemouth',                'Brentford',
                 'Brighton',                  'Chelsea',
           'Crystal Palace',                  'Everton',
                   'Fulham',             'Ipswich Town',
           'Leicester City',                'Liverpool',
          'Manchester City',        'Manchester United',
         'Newcastle United',        'Nottingham Forest',
              'Southampton',        'Tottenham Hotspur',
          'West Ham United',                   'Wolves',
          'Athletic Bilbao',          'Atletico Madrid',
                'Barcelona',               'Real Betis',
               'Celta Vigo',         'Deportivo Alaves',
                 'Espanyol',                   'Getafe',
                   'Girona',               'Las Palmas',
                  'Leganes',                 'Mallorca',
                  'Osasuna',           'Rayo Vallecano',
              'Real Madrid',            'Real Sociedad',
                  'Sevilla',                 'Valencia',
               'Valladolid',               'Villarreal',
      'Paris Saint-Germain',                'Marseille',
                   'Monaco',                    'Lille',
                     'Lyon',                     'Nice',
                     'Lens',                   'Rennes',
                    'Reims',               'Strasbourg',
                    'Brest',                   'Nantes',
                 'Toulouse',              'Montpellier',
                  'Auxerre',                   'Angers',
                 'Le Havre',            'Saint-Etienne',
                    'Inter',                 'AC Milan',
                 'Juventus',                 'Atalanta',
                     'Roma',                   'Napoli',
               'Fiorentina',                  'Bologna',
                   'Torino',                  'Udinese',
                   'Empoli',                    'Genoa',
                    'Parma',                     'Como',
            'Hellas Verona',                 'Cagliari',
                    'Lecce',                    'Monza',
                  'Venezia',                    'Lazio']
Length: 96, dtype: str

In [219]:
print(df_players["Comp"].unique())
print(df_injuries["league"].unique())

<ArrowStringArray>
['eng Premier League', 'es La Liga', 'it Serie A', 'fr Ligue 1',
 'de Bundesliga']
Length: 5, dtype: str
<ArrowStringArray>
['Bundesliga', 'Premier League', 'La Liga', 'Ligue 1', 'Serie A']
Length: 5, dtype: str

Los nombres de clubes no coinciden siempre, aunque las ligas sí se pueden normalizar fácilmente.

In [220]:
df_players["Comp"] = df_players["Comp"].replace({
    "eng Premier League": "Premier League",
    "es La Liga": "La Liga",
    "it Serie A": "Serie A",
    "fr Ligue 1": "Ligue 1",
    "de Bundesliga": "Bundesliga"
})

print(df_players["Comp"].unique())

<ArrowStringArray>
['Premier League', 'La Liga', 'Serie A', 'Ligue 1', 'Bundesliga']
Length: 5, dtype: str

Los nombres de los equipos no coinciden siempre

In [221]:
clubes = {
    "Manchester Utd": "Manchester United",
    "Nottingham": "Nottingham Forest",
    "Athletic Club": "Athletic Bilbao",
    "Atlético Madrid": "Atletico Madrid",
    "Milan": "AC Milan",
    "Paris SG": "Paris Saint-Germain",
    "Freiburg": "SC Freiburg",
    "St Pauli": "FC St. Pauli",
    "Leverkusen": "Bayer Leverkusen",
    "Gladbach": "Borussia Monchengladbach",
    "Wolves": "Wolverhampton Wanderers"
}

print(df_players["Squad"].isin(df_injuries["club"]).sum())

2246

Ahora necesitamos saber qué nombres de clubes no coinciden

In [222]:
print(df_players.loc[
    ~df_players["Squad"].isin(df_injuries["club"]),
    "Squad"
].unique())

<ArrowStringArray>
[  'Saint-Étienne',          'Alavés',           'Milan',        'Freiburg',
        'Dortmund',      'Leverkusen',        'St Pauli',   'Athletic Club',
      'Nottingham',       'Newcastle',         'Leganés',        'West Ham',
 'Atlético Madrid',  'Manchester Utd',       'Frankfurt',       'Wolfsburg',
        'Paris SG',       'Tottenham',          'Bochum',      'Heidenheim',
       'Stuttgart',        'Gladbach']
Length: 22, dtype: str

In [223]:
clubes = {
    "Saint-Étienne": "Saint-Etienne",
    "Alavés": "Deportivo Alaves",
    "Milan": "AC Milan",
    "Freiburg": "SC Freiburg",
    "Dortmund": "Borussia Dortmund",
    "Leverkusen": "Bayer Leverkusen",
    "St Pauli": "FC St. Pauli",
    "Athletic Club": "Athletic Bilbao",
    "Nottingham": "Nottingham Forest",
    "Newcastle": "Newcastle United",
    "Leganés": "Leganes",
    "West Ham": "West Ham United",
    "Atlético Madrid": "Atletico Madrid",
    "Manchester Utd": "Manchester United",
    "Frankfurt": "Eintracht Frankfurt",
    "Wolfsburg": "VfL Wolfsburg",
    "Paris SG": "Paris Saint-Germain",
    "Tottenham": "Tottenham Hotspur",
    "Bochum": "VfL Bochum",
    "Heidenheim": "FC Heidenheim",
    "Stuttgart": "VfB Stuttgart",
    "Gladbach": "Borussia Monchengladbach"
}

In [224]:
df_players["Squad"] = df_players["Squad"].replace(clubes)

In [225]:
print(df_players.loc[
    ~df_players["Squad"].isin(df_injuries["club"]),
    "Squad"
].unique())

<ArrowStringArray>
[]
Length: 0, dtype: str

Ahora comprobamos los nombres de jugadores

In [226]:
print(df_players["Player"].isin(df_injuries["player_name"]).sum())

1407

In [227]:
print(df_players.loc[
    ~df_players["Player"].isin(df_injuries["player_name"]),
    "Player"
].unique())

<ArrowStringArray>
[        'Max Aarons',     'Rodrigo Abajas',     'James Abankwah',
  'Keyliane Abdallah',   'Yunis Abdelhamid',      'Nabil Aberdin',
  'Oliver Abildgaard',     'Matthis Abline',              'Abner',
 'Federico Accornero',
 ...
     'Alessio Zerbin',     'Cedric Zesiger',   'Michael Zetterer',
        'Nathan Zeze',       'Melvin Zinga',         'Luck Zogbé',
    'Aristide Zossou',   'Martín Zubimendi',       'Edhy Zuliani',
        'Milan Đurić']
Length: 1373, dtype: str

In [228]:
print(df_players["Player"].isin(df_injuries["player_name"]).sum())

1407

In [229]:
print(
    df_players[["Player", "Squad"]]
    .apply(tuple, axis=1)
    .isin(
        df_injuries[["player_name", "club"]]
        .apply(tuple, axis=1)
    )
    .sum()
)

1403

Ahora localizo esos 4 casos para ver si son transferencias, diferencias de datos o algún error de normalización.

In [230]:
pares = df_players[["Player", "Squad"]].drop_duplicates()

pares = pares[
    pares["Player"].isin(df_injuries["player_name"])
]

print(
    pares[
        ~pares.apply(tuple, axis=1).isin(
            df_injuries[["player_name", "club"]]
            .drop_duplicates()
            .apply(tuple, axis=1)
        )
    ]
)

              Player                Squad
1359     Joshua King               Fulham
2227           Rodri           Real Betis
2234  Dani Rodríguez             Mallorca
2718         Vitinha  Paris Saint-Germain

Ahora quiero comprobar qué club aparece en df_injuries para esos cuatro jugadores. Así no vamos a adivinar ni modificar datos incorrectamente.

In [231]:
print(
    df_injuries[
        df_injuries["player_name"].isin([
            "Joshua King",
            "Rodri",
            "Dani Rodríguez",
            "Vitinha"
        ])
    ][["player_name", "club", "league"]]
)

          player_name             club          league
6772            Rodri  Manchester City  Premier League
6773            Rodri  Manchester City  Premier League
8896   Dani Rodríguez        Barcelona         La Liga
8897   Dani Rodríguez        Barcelona         La Liga
8898   Dani Rodríguez        Barcelona         La Liga
11354     Joshua King         Toulouse         Ligue 1
15299         Vitinha            Genoa         Serie A
15300         Vitinha            Genoa         Serie A
15301         Vitinha            Genoa         Serie A

In [232]:
print(df_injuries["player_name"].value_counts().head(10))

player_name
Carney Chukwuemeka    14
Noah Okafor           10
Michael Folorunsho    10
Moritz Jenz            8
Florian Grillitsch     8
Massadio Haïdara       8
Davide Calabria        8
Álvaro Morata          8
Nicolò Zaniolo         8
Dayot Upamecano        6
Name: count, dtype: int64

Un jugador puede tener varios registros de lesiones en df_injuries. Por ejemplo:

Carney Chukwuemeka → 14 lesiones
Noah Okafor → 10
Michael Folorunsho → 10
Moritz Jenz → 8

In [233]:
print(df_injuries[["Days", "Games missed"]].dtypes)

Days              str
Games missed    int64
dtype: object

In [234]:
print(df_injuries[["Days", "Games missed"]].head(10))

         Days  Games missed
3267  56 days            10
3268  26 days             4
3269   9 days             1
3270  55 days            13
3271  63 days             6
3272   5 days             2
3273  76 days            12
3274   3 days             1
3275   7 days             1
3276   6 days             1

In [235]:
df_injuries["Days"] = df_injuries["Days"].str.replace(" days", "").astype(int)

print(df_injuries[["Days", "Games missed"]].dtypes)

Days            int64
Games missed    int64
dtype: object

Queremos poder sumar los días de todas las lesiones de un jugador.

In [236]:
df_injuries_agg = df_injuries.groupby(
    ["player_name", "club"]
)[["Days", "Games missed"]].sum().reset_index()

In [237]:
print(df_injuries_agg.head())

print(df_injuries_agg.shape)

             player_name             club  Days  Games missed
0  Aaron Ciammaglichella           Torino   110            19
1        Aaron Cresswell  West Ham United    11             2
2           Aaron Hickey        Brentford    89            13
3         Aaron Ramsdale          Arsenal    47             7
4         Aaron Ramsdale      Southampton    47             7
(1802, 4)

Ahora tenemos 1.802 combinaciones jugador + club con lesiones, donde cada fila representa el total de:

Days → días de baja acumulados.
Games missed → partidos perdidos acumulados.

Vamos a unir:

df_players

Player
Pos
Squad
Comp
MP
Starts
Min

con:

df_injuries_agg

player_name
club
Days
Games missed

In [238]:
df_final = df_players.merge(
    df_injuries_agg,
    left_on=["Player", "Squad"],
    right_on=["player_name", "club"],
    how="left"
)

In [239]:
print(df_final.shape)

print(df_final.head())

(2854, 11)
              Player Pos        Squad            Comp  MP  Starts  Min  \
0         Max Aarons  DF  Bournemouth  Premier League   3       1   86
1         Max Aarons  DF     Valencia         La Liga   4       1  120
2     Rodrigo Abajas  DF     Valencia         La Liga   1       1   65
3     James Abankwah  DF      Udinese         Serie A   6       0   88
4  Keyliane Abdallah  FW    Marseille         Ligue 1   1       0    3

  player_name club  Days  Games missed
0         NaN  NaN   NaN           NaN
1         NaN  NaN   NaN           NaN
2         NaN  NaN   NaN           NaN
3         NaN  NaN   NaN           NaN
4         NaN  NaN   NaN           NaN

In [240]:
print(df_final["Days"].isna().sum())
print(df_final["Days"].notna().sum())
print(df_final[["Days", "Games missed"]].isna().sum())

1451
1403
Days            1451
Games missed    1451
dtype: int64

Esto confirma algo muy importante:

2.854 jugadores en total.
1.403 jugadores tienen al menos un registro de lesión.
1.451 jugadores no tienen ningún registro de lesión.
1.403 + 1.451 = 2.854, así que el merge está perfecto.

In [241]:
df_final[["Days", "Games missed"]] = df_final[["Days", "Games missed"]].fillna(0)

In [242]:
print(df_final[["Days", "Games missed"]].isna().sum())

Days            0
Games missed    0
dtype: int64

In [243]:
df_final

,Player,Pos,Squad,Comp,MP,Starts,Min,player_name,club,Days,Games missed
0,Max Aarons,DF,Bournemouth,Premier League,3,1,86,NaN,NaN,0.0,0.0
1,Max Aarons,DF,Valencia,La Liga,4,1,120,NaN,NaN,0.0,0.0
2,Rodrigo Abajas,DF,Valencia,La Liga,1,1,65,NaN,NaN,0.0,0.0
3,James Abankwah,DF,Udinese,Serie A,6,0,88,NaN,NaN,0.0,0.0
4,Keyliane Abdallah,FW,Marseille,Ligue 1,1,0,3,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,MF,Arsenal,Premier League,30,26,2325,Martin Ødegaard,Arsenal,62.0,15.0
2850,Leo Østigård,DF,Hoffenheim,Bundesliga,11,11,927,Leo Østigård,Hoffenheim,12.0,2.0
2851,Leo Østigård,DF,Rennes,Ligue 1,16,14,1227,Leo Østigård,Rennes,12.0,2.0
2852,Milan Đurić,FW,Monza,Serie A,18,13,1270,NaN,NaN,0.0,0.0
2853,Milan Đurić,FW,Parma,Serie A,9,3,268,NaN,NaN,0.0,0.0

In [244]:
df_final = df_final.drop(columns=["club", "player_name"])

In [245]:
df_final

,Player,Pos,Squad,Comp,MP,Starts,Min,Days,Games missed
0,Max Aarons,DF,Bournemouth,Premier League,3,1,86,0.0,0.0
1,Max Aarons,DF,Valencia,La Liga,4,1,120,0.0,0.0
2,Rodrigo Abajas,DF,Valencia,La Liga,1,1,65,0.0,0.0
3,James Abankwah,DF,Udinese,Serie A,6,0,88,0.0,0.0
4,Keyliane Abdallah,FW,Marseille,Ligue 1,1,0,3,0.0,0.0
...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,MF,Arsenal,Premier League,30,26,2325,62.0,15.0
2850,Leo Østigård,DF,Hoffenheim,Bundesliga,11,11,927,12.0,2.0
2851,Leo Østigård,DF,Rennes,Ligue 1,16,14,1227,12.0,2.0
2852,Milan Đurić,FW,Monza,Serie A,18,13,1270,0.0,0.0
2853,Milan Đurić,FW,Parma,Serie A,9,3,268,0.0,0.0

-

-

AHORA LO QUE HAREMOS SERÁ LLEVAR TODOS ESTOS DATOS A SQL